version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 10"
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
