version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    default_reviewers:
      - c1rrus
    ignored_updates:
      - match:
          dependency_name: "@types/node"
          version_requirement: "> 8"
    commit_message:
      prefix: chore
