version: 1
update_configs:
  # Security updates to (non-dev) dependencies
  # use "fix" prefix in commit message (so that
  # they trigger automated package releases).
  - package_manager: javascript
    directory: /
    update_schedule: live
    ignored_updates:
      - match:
          dependency_name: "@types/node"
          version_requirement: "> 8"
    automerged_updates:
      - match:
          update_type: "all"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
